apiVersion: v1
kind: Service
metadata:
  name: mongo-external
  namespace: mongo
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: mongo-port-external
      nodePort: 32463
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    name: mongodb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
